### ISSUE TITLE
initVueRouterGuard missing vueRouter

### ISSUE THREAD

**Issue by fnfilho** [Glovo/vue-multianalytics#1]
Hey guys.

Nice work with this package!

I am getting "ReferenceError: vueRouter is not defined" inside the initVueRouterGuard function. According to the docs, we were suppose to have the params:

```
@param Vue - The Vue instance
@param vueRouter - The Vue router instance to attach guard
@param {string[]} ignoredViews - An array of route name to ignore
```

But the function is only receiving `initVueRouterGuard = function (Vue, routing)` but is using vueRouter on the inside.

**Comment by willylatorre** [comment]
Hi @fnfilho,
The correct way to initialize the vueRouter support is passing an object with multiple properties as defined in the [vue-router integration](https://github.com/Glovo/vue-multianalytics#vuerouter-integration) section of the readme.

But yes, we've updated the documentation to explain it better. 

Thanks a lot for noticing it!

**Comment by fnfilho** [comment]
Hey! @willylatorre.

Not sure what I am doing wrong than...

```
**main.js**
import Vue from 'vue'
import VueMultianalytics from 'vue-multianalytics'
import VueRouter from 'vue-router'

// Router configurations
// -------
import {routes} from './routes'

const router = new VueRouter({
  mode: 'history',
  routes: routes
})

// Analytics
// -------
import {analytics} from './analytics'

Vue.use(VueMultianalytics, {
  modules: {
    ga: analytics.gaConfig,
    mixpanel: analytics.mixpanelConfig
  },
  routing: {
    vueRouter: router,
    preferredProperty: 'name',
    ingoredViews: ['homepage']
  }
})
```

after compiling, this is what I get on the browser

vue-multianalytics.min.js?96f8:1 Uncaught ReferenceError: vueRouter is not defined
    at m (eval at <anonymous> (app.js:3885), <anonymous>:1:1379)
    at Object.b [as install] (eval at <anonymous> (app.js:3885), <anonymous>:1:1102)
    at Function.Vue.use (eval at <anonymous> (app.js:606), <anonymous>:3870:22)
    at eval (eval at <anonymous> (app.js:2280), <anonymous>:61:15)
    at Object.<anonymous> (app.js:2280)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at Object.<anonymous> (app.js:587)
    at __webpack_require__ (app.js:556)
    at app.js:579

which leads to the code `vueRouter.afterEach` at initVueRouterGuard.js. I don't think the variable vueRouter is being set inside this function, is it?

**Comment by fnfilho** [comment]
I just saw the update on the docs, shouldn't the code at initVueRouterGuard.js be `routing.vueRouter.afterEach` ?

**Comment by willylatorre** [comment]
Yeah, you are again right. I don't know what happened there, I missed that during the refactor.
Changes done and uploaded!

**Comment by fnfilho** [comment]
Great! Thanks for the quick reply!
