### ISSUE TITLE
v1.9.6 broken with Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by newenegue** [Glovo/vue-multianalytics#30]
I've confirmed that v1.9.4 is working correctly.  Only until I used the latest version from npm (v1.9.6) did it break.

I found this issue on stackoverflow that suggested a hoisted function error.
https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined

**Comment by albertor24** [comment]
I can confirm. Seeing exactly the same issue using the latest build, and using 1.9.4 does work fine.

**Comment by Frzurita** [comment]
Hi! yes, we added async await. We'll fix it soon. Thanks for the support

**Comment by gwilakers** [comment]
Anything I can help with move this along?

**Comment by romainframe** [comment]
Hi all !

Having the same issue but still on v1.9.4 ...
Extract of my package.json:
> -    "vue-multianalytics": "^1.9.4",
> -    "babel-plugin-transform-runtime": "^6.23.0",

The error appeared without running npm install, but only rebuilding my app (npm build...).

Is that possible while building, babel / webpack calls external modules? and so taking a latest version that introduce the bug.

Happy to help if possible

**Comment by hmexx** [comment]
Can confirm that downgrading to 1.9.4 does not seem to work anymore. Not sure what's going on. Webpack does not hot reload when I downgrade which would indicate that the code used isn't changing when I change versions.

**Comment by gwilakers** [comment]
@hmexx @romainframe Did you completely remove your node_modules directory when reinstalling? I downgraded to 1.9.4 a few days ago and that seemed to fix the issue for me. Same babel-plugin-transform-runtime version as well.

**Comment by hmexx** [comment]
@gwilakers removing node_modules seems to have done the trick... which is weird because I've never had to do that before when downgrading a dependency, but all good here. 

Back to work!

**Comment by gwilakers** [comment]
@hmexx Good to hear! Npm can be a little finicky sometimes when it comes to changing package versions. Always a good idea to just remove the modules and start fresh 👍.

**Comment by romainframe** [comment]
Thanks a lot @gwilakers !

I was building with Docker so the node_modules directory was always empty at start.

But inspecting the package.json of vue-multianalytics module I saw this:

> RUN head node_modules/vue-multianalytics/package.json
>  ---> Running in 66eda2787e65
> {
>   "_from": "vue-multianalytics@^1.9.4",
>   "_id": "vue-multianalytics@1.9.6",
>   "_inBundle": false,
>   "_integrity": "sha512-z0YwEUvVsLAaicOoZX7P7VnVO/sm29q1AOIcoBymUBgX+E7Jau44V1eA/xG21vCJjktH5EudMZ8t2WnqtVWlVg==",
>   "_location": "/vue-multianalytics",
>   "_phantomChildren": {},
>   "_requested": {
>     "type": "range",
>     "registry": true,

From this I understood I needed to remove "^" from my project package:

> - "vue-multianalytics": "^1.9.4",
> + "vue-multianalytics": "1.9.4",

And now the module is fine:

> RUN head node_modules/vue-multianalytics/package.json
>  ---> Running in 05f078fccafa
> {
>   "_from": "vue-multianalytics@1.9.4",
>   "_id": "vue-multianalytics@1.9.4",
>   "_inBundle": false,
>   "_integrity": "sha512-c2x6o1B5a+8G9JYMhEOqM5mGv9HgAT/tjbNyhjwjevZ2gy1qyottwoLYkMpkPXFS7jHCgEuPa5MT990kw+QJEA==",
>   "_location": "/vue-multianalytics",
>   "_phantomChildren": {},
>   "_requested": {
>     "type": "version",
>     "registry": true,

Did the trick! Thanks again

**Comment by marchofreason** [comment]
Is this package going to be fixed for 1.9.6? I'm implementing this into my app and I am worried about the longevity of this package.

Great work on this so far though!

**Comment by tdrach** [comment]
Downgraded to `1.9.4` and removes the error for the time being. 

``` 
yarn add vue-multianalytics@1.9.4
```

**Comment by irrg** [comment]
Seconding the question, will this be fixed soon?
