### ISSUE TITLE
mixpanel setUsername is not working

### ISSUE THREAD

**Issue by tksumanth1994** [Glovo/vue-multianalytics#44]
While I was debugging the issue, I found that `mixpanel.identity` is returning `undefined` [in this line](https://github.com/Glovo/vue-multianalytics/blob/35fab0e81ce9b084d2bc0973a47b5b3082e745b7/src/modules/MixpanelModule.js#L93), because of which it is not able to set the username.

On further googling, [mixpanel support says that this can happen if the script has not loaded yet](https://help.mixpanel.com/hc/en-us/articles/115004499223-TypeError-undefined-is-not-a-function). But I checked using the `loaded` attribute in the config & it's working fine. Not sure what the issue is.

Please help.

**Comment by DineshSrisrimal** [comment]
I think Mixpanel needs identification and only then it sets the username. You will have to do this before setting the username.
`this.$ma.identify({ userId: UNIQUE_ID })`
Did you try this?

**Comment by tksumanth1994** [comment]
Thanks! This worked! 👍
