### ISSUE TITLE
VueMultianalytics log when production mode

### ISSUE THREAD

**Issue by goalie7** [Glovo/vue-multianalytics#5]
I got these logs in the console when the app is deployed in production mode, is this normal?

![image](https://cloud.githubusercontent.com/assets/7350351/26732114/c1696f56-47b6-11e7-9b80-4476c6a1cc9d.png)

**Comment by yassineb** [comment]
Yes, it's normal if you have the debug mode enabled (https://github.com/Glovo/vue-multianalytics#configuration).
