### ISSUE TITLE
Custom properties on trackEvent()

### ISSUE THREAD

**Issue by marcusos** [Glovo/vue-multianalytics#6]
Hello everyone, Greate Plugin! I hava a question:

How can I set custom properties on the trackEvent method?

I know that with segement is possible to set custom properties.

**Comment by willylatorre** [comment]
Hey @marcusos ,
The trackEvent action accepts a `properties` object to set your custom properties.
https://github.com/Glovo/vue-multianalytics/blob/master/src/modules/SegmentModule.js#L63

So you just need to do
```
let props = { action: "Event A", properties: { propA: true, propB: "whatever"}}
this.$ma.trackEvent(props)
```
